package br.ufc.smd.italoboss.socketjack.clientside;

import br.ufc.smd.italoboss.socketjack.Player;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author italo_boss
 */
public class ClientGUI extends javax.swing.JFrame  {
    
    protected final String port;
    protected final String address;
    protected Socket socket;
    protected ObjectInputStream input;
    protected ObjectOutputStream output;
    protected Player me;
    /**
     * Creates new form ClientGUI
     * @param address
     * @param port
     */
    public ClientGUI(String address, String port) {
        this.address = address;
        this.port = port;
        initComponents();
        connectToHost();
    }
    
    public ClientGUI(String address, String port, Player player) {
        this.address = address;
        this.port = port;
        this.me = player;
        initComponents();
        connectToHost();
    }
    
    private void connectToHost()
    {
        new ClientReceiver(this).start();
    }
    
    public void writeServerMsg(String message)
    {
        lbMsgServer.setText(message);
    }
    
    public void writePlayerName(String name)
    {
        lbPlayerName.setText(name);
    }
    
    public void enableButtons(boolean enabled)
    {
        btFinish.setEnabled(enabled);
        btHit.setEnabled(enabled);
        btStand.setEnabled(enabled);
        btDouble.setEnabled(enabled);
    }
    
    private void hitAction()
    {
        try {
            output.writeObject(Player.HIT + "\n");
//            String message = String.valueOf(input.readObject());
            writeServerMsg("HITTING!");
        } 
        catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void standAction()
    {
        try {
            output.writeObject(Player.STAND + "\n");
//            String message = String.valueOf(input.readObject());
            writeServerMsg("YOU ARE READY. WAITING FOR RESULT...");
            enableButtons(false);
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void doubleAction()
    {
        try {
            me.setBet(me.getBet()*2);
            output.writeObject(Player.DOUBLE + "\n");
//            String message = String.valueOf(input.readObject());
            writeServerMsg("DOUBLING DOWN! YOU ARE READY. WAITING FOR RESULT...");
            enableButtons(false);
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void finishAction()
    {
        try {
            output.writeObject("END" + "\n");
            input.close();
            output.close();
            socket.close();
            enableButtons(false);
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHit = new javax.swing.JButton();
        btStand = new javax.swing.JButton();
        btDouble = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbMsgServer = new javax.swing.JLabel();
        lbPlayerName = new javax.swing.JLabel();
        btFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btHit.setText("HIT");
        btHit.setEnabled(false);
        btHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitActionPerformed(evt);
            }
        });

        btStand.setText("STAND");
        btStand.setEnabled(false);
        btStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStandActionPerformed(evt);
            }
        });

        btDouble.setText("DOUBLE");
        btDouble.setEnabled(false);
        btDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoubleActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222)));

        lbMsgServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMsgServer.setText("MESSAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMsgServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMsgServer, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbPlayerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayerName.setText("PLAYER");

        btFinish.setText("Finish");
        btFinish.setEnabled(false);
        btFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btHit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btStand, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btDouble, btHit, btStand});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFinish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btStand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btDouble, btHit, btStand});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitActionPerformed
        hitAction();
    }//GEN-LAST:event_btHitActionPerformed

    private void btStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStandActionPerformed
        standAction();
    }//GEN-LAST:event_btStandActionPerformed

    private void btDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoubleActionPerformed
        doubleAction();
    }//GEN-LAST:event_btDoubleActionPerformed

    private void btFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinishActionPerformed
        finishAction();
    }//GEN-LAST:event_btFinishActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDouble;
    private javax.swing.JButton btFinish;
    private javax.swing.JButton btHit;
    private javax.swing.JButton btStand;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMsgServer;
    private javax.swing.JLabel lbPlayerName;
    // End of variables declaration//GEN-END:variables
}
